### ISSUE TITLE
File name not compatible with windows

### ISSUE THREAD

**Issue by edgardmessias** [hiqdev/yii2-thememanager#1]
The file `src/messages/ru/hiqdev:thememanager.php` is not compatible with windows.

Windows not allow ':' in file name.

**Comment by hiqsol** [comment]
Ok, let's discuss options:

- dot `.`
- underscore `_`
- minus `-`
- else?

Slash and backslash not an options.

**Comment by SilverFire** [comment]
Voting for dot

**Comment by edgardmessias** [comment]
Dot

**Comment by hiqsol** [comment]
Renamed.
