### ISSUE TITLE
how to use themes

### ISSUE THREAD

**Issue by masihfathi** [hiqdev/yii2-thememanager#2]
how can i use "yii2-thememanager" in my projects?

**Comment by hiqsol** [comment]
Take a closer look to [hisite](https://hisite.hiqdev.com).

There is the template application using this approach - [hisite-template](https://github.com/hiqdev/hisite-template).

There are couple of real applications using this approch, e.g. [asset-packagist](https://github.com/hiqdev/asset-packagist)

You can start with hisite-template. Try to deploy it on your side.
Try to switch to other theme. Hope this will help.
We can give you more information for more specific questions.
